#include <iostream.h>
#include<conio.h>
void main( void )
{
clrscr();
char riya;
do{
	int one, two, three, four, five, six, seven, eight, nine, ten, eleven, twelve, thirteen, fourteen, fifteen, sixteen, seventeen, eighteen, nineteen, twenty;
	cout<< "Q.8 x 8\nAns:";
	cin>> one;
	{
		if ( one == 64 )
			cout<< "Good\n";

	else
		cout<< " Sorry\n";
	}
	cout<< "Q.9 x 4\nAns:";
	cin>> two;
	{
		if ( two == 36 )
			cout<< " Great Job, Keep it up!\n";
	else
		cout<< " Try Harder, bud!\n";
	}
	cout<< "Q. 8 x 5\nAns: ";
	cin>> three;
	{
		if ( three == 40 )
			cout<< " Awsome!\n";

	else
		cout<< " Ummmmm...\n";
	}
	cout<< "Q. 9 x 2\nAns:";
	cin>> four;
	{
		if ( four == 18 )
			cout<< "Your gonna be the next Einstein\n";
		else
			cout<< " Who the heck is your teacher!?\n";
	}
	cout<< "Q. 5 x 5\nAns: ";
	cin>> five;
	{
		if ( five == 25 )
			cout<< " There he is, get him!!!\n";

		else
			cout<< " No way, who is your teacher!?\n";
	}
	cout<< "Q. 4 x 8\nAns: ";
	cin>> six;
	{
		if ( six == 32 )
			cout<< " Your too good!\n ";
		else
			cout<< " Come on\n ";
	}
	cout<< "Q. 12 x 12\nAns: ";
	cin>> seven;
	{
		if ( seven == 144 )
			cout<< " That was really impressive!\n";
		else
			cout<< " Keep Trying!\n";
	}
	cout<< "Q. 6 x 5\nAns: ";
	cin>> eight;
	{
		if ( eight == 30 )
			cout<< " Really Cool!\n";
		else
			cout<< " Sorry\n";
	}
	cout<< "Q. 4 x 4\nAns: ";
	cin>> nine;
	{
		if ( nine == 16 )
			cout<< " Your too much!\n";
			else
			cout<< " C'mon, you can get the next one, I know it!\n";
	}
	cout<< " Last one\n ";
	cout<< "Q. 100 x 100\nAns: ";
	cin>> ten;
	{
		if ( ten == 10000 )
			cout<< " OH MY GOSH, HE IS SO INCREADABLY SMART!!!\n";
		else
			cout<< " Sorry man, why dont you try over again?\n";
	}
	cout<< "Q. 11 x 11\nAns:";
	cin>> eleven;
	{
		if ( eleven == 121 )
			cout<< " Super\n";
		else
			cout<< " Nope, Keep Trying\n";
	}
	cout<< "Q. 4 x 7\nAns: ";
	cin>> twelve;
	{
		if ( twelve == 28 )
			cout<< " Wow\n ";
		else
			cout<< " Thats ok, just keep at it\n";
	}
	cout<< "Q. 7 x 7\nAns: ";
	cin>> thirteen;
	{
		if ( thirteen == 49 )
			cout<< " Isn't this fun?\n";
			else
			cout<< " That is what this program is for.\n";
	}
	cout<< "Q. 8 x 7\nAns:";
	cin>> fourteen;
	{
		if ( fourteen == 56 )
			cout<< " Stupendious\n";
		else
			cout<< " Can you feel the disappointment?\n";
	}
	cout<< "Q. 9 x 7\nAns: ";
	cin>> fifteen;
	{
		if ( fifteen == 63 )
			cout<< " Tight\n";
		else
			cout<< " Ok, just keep at it\n";
	}
	cout<< "Q. 5 x 7\nAns: ";
	cin>> sixteen;
	{
		if ( sixteen == 35 )
			cout<< " Bwa ha ha ha, you so cool!\n";
		else
			cout<< " Try a bit harder.\n";
	}
	cout<< "Q. 3 x 9\nAns: ";
	cin>> seventeen;
	{
		if ( seventeen == 27 )
			cout<< " You are almost as good as me~~~\n";
		else
			cout<< " Thats ok\n";
	}
	cout<< "Q. 9 x 6\nAns: ";
	cin>> eighteen;
	{
		if ( eighteen == 54 )
			cout<< " You are better than I thought...\n";
		else
			cout<< " Keep working\n";
	}
	cout<< "Q. 7 x 2\nAns: ";
	cin>> nineteen;
	{
		if ( nineteen == 14 )
			cout<< " You are really good at math\n";
		else
			cout<< " Everyone makes mistakes.\n";
	}
	cout<< "Q. 10 x 10\nAns: ";
		cin>> twenty;
	{
		if ( twenty == 100 )
			cout<< " You have earned the rank of Einstein!\n";
		else
			cout<< " Try again and see if you can get to be Einstein...\n";
		     cout<<"######  \t THANK YOU FOR PLAYING  \t ######";
		  cout<<"\n\nif you want to practice more math then press y:";
		  cin>>riya;
		  }
		  }
		  while (riya=='y');

	getch();
}